apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: mjolnir
    path: /mnt/storage/iot/influxdb
    readOnly: false
