apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: iot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: influxdb-nfs-pv
