apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: iot
type: Opaque
stringData:
  admin-username: admin
  admin-password: changeme123
  admin-token: my-super-secret-admin-token
  org: iot
  bucket: iot-data